// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://euuvfzxwkzvdfrtzakde.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV1dXZmenh3a3p2ZGZydHpha2RlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2MjQ3MDQsImV4cCI6MjA2ODIwMDcwNH0.FA9tLAfOmOrvZpRYn-FyJzq-OuwPq_e9UvHR4_l0znA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});